---
- name: "Get configuration directory's .git stats"
  stat: path={{nginx_drupal_config_path}}/.git
  register: nginx_drupal_config_path_dot_git
- name: "Remove existing configurarion directory"
  file: path={{nginx_drupal_config_path}} state=absent
  when: not nginx_drupal_config_path_dot_git.stat.exists
- name: "Checkout configuration directory"
  git: dest={{nginx_drupal_config_path}} repo={{nginx_drupal_git.repo}} version={{nginx_drupal_git.version}} force=yes
  when: (not nginx_drupal_config_path_dot_git.stat.exists) or (nginx_drupal_git.force_checkout|default(False))
  notify:
   - reload nginx
- name: "Remove example.com configuration file"
  file: path={{nginx_drupal_config_path}}/sites-available/example.com.conf state=absent